[project]
name = "odoo-addons-oca-module-composition-analysis"
version = "18.0.20260403.0"
dependencies = [
    "odoo-addon-odoo_repository==18.0.*",
    "odoo-addon-odoo_repository_migration==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
